services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/quanghuy10999/n8n-render
    branch: master
    dockerCommand: "docker run -p 5678:5678 n8nio/n8n"
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: http
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://n8n-myproject.onrender.com
